export const PROVIDERS: { id: string; label: string; placeholder: string }[] = [
  { id: 'openai', label: 'OpenAI API Key', placeholder: 'sk-...' },
  { id: 'groq', label: 'Groq API Key', placeholder: 'gsk_...' },
  { id: 'gemini', label: 'Gemini API Key', placeholder: 'AIza...' },
];

export const TONES: string[] = [
  'professional',
  'witty',
  'promotional',
  'casual',
  'formal',
  'humorous',
  'inspirational',
  'educational'
];

export const defaultStyles: string[] = [
  "Interpolate emojis",
  "Neutral tone",
  "Interpolate relevant hashtags",
  "No announcements",
  "Do not include external links",
  "Do not include facts or trivia",
];

export const writingStyles: string[] = [
  ...defaultStyles,
  "Include cultural references",
  "Abundant emojis",
  "No emojis",
  "Completely exclude hashtags",
  "Mention other users",
  "Do not mention other users",
  "Use formal language",
  "Use colloquial language",
  "Include links to web pages",
  "Include inspirational quotes",
  "Avoid any type of quote",
  "Ask rhetorical questions",
  "Do not ask questions",
  "Include data and statistics",
  "Avoid data and statistics",
  "Use technical or industry-specific jargon",
  "Keep language simple and accessible",
  "Use humor or sarcasm",
  "Maintain a serious tone",
  "Include calls to action (CTAs)",
  "Avoid any type of call to action",
  "Employ storytelling",
  "Avoid narratives, stick to facts and statements",
  "Reference current events",
  "Do not reference current events",
  "Use metaphors and analogies",
  "Avoid metaphors and analogies",
  "Create suspense or intrigue",
  "Start with a question",
  "Do not start with a question",
  "Use alliteration",
  "Avoid alliteration",
  "Include a fact or trivia",
  "Use a positive tone",
  "Use a negative or critical tone",
  "Express personal opinions",
  "Avoid personal opinions",
  "Include wordplay or puns",
  "Avoid wordplay or puns",
  "Use rhymes",
  "Do not use rhymes",
  "Quote famous people",
  "Do not quote famous people",
  "Tag a celebrity or well-known figure",
  "Avoid tagging well-known figures",
  "Use popular culture references",
  "Avoid pop culture references",
  "Incorporate an announcement",
  "Discuss a product or service",
  "Do not discuss products or services",
  "Include a personal anecdote",
  "Avoid personal anecdotes",
  "Promote an event",
  "Do not promote events",
  "Share user-generated content",
  "Avoid user-generated content",
  "Use a conversational tone",
  "Avoid a conversational tone",
  "Include a contest or giveaway",
  "No contests or giveaways",
  "Promote a blog post or article",
  "Avoid promoting blog posts or articles",
];

export const MODELS = [
  { id: 'gpt-4o-mini', provider: 'openai' },
  { id: 'gpt-4', provider: 'openai' },
  { id: 'gpt-3.5-turbo', provider: 'openai' },
  { id: 'groq:meta-llama/llama-guard-4-12b', provider: 'groq' },
  { id: 'groq:openai/gpt-oss-120b', provider: 'groq' },
  { id: 'groq:openai/gpt-oss-20b', provider: 'groq' },
  { id: 'gemini-2.5-flash', provider: 'gemini' },
  { id: 'gemini-2.5-pro', provider: 'gemini' },
];
